language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-22.0.1

    # The SDK version used to compile your project
    - android-22

    # Additional components
    # - extra-google-google_play_services
    # - extra-google-m2repository
    - extra-android-m2repository

before_script:
    #Create blank API key so that the build won't fail
    - printf "VOAT_API_KEY = \"\"\nVOAT_FABRIC_KEY = \"\"\n" > gradle.properties
    - chmod +x gradlew

#Ignore the fabric step, since we do not have a legit API key for Fabric
script: "./gradlew build -x fabricGenerateResourcesRelease"
